### ISSUE TITLE
Is there some way of getting a notification when a job is done?

### ISSUE THREAD

**Issue by jave** [msolli/proletarian#23]
Is there some way of getting a notification when a job is done?

For instance: 
- start a long running job, like a couple of minutes
- when the job is done, notify the user

I could of course put the notification at the end of the worker handler, but it seems a bit off.

**Comment by binodsarkar** [comment]
I am using this in my production. And facing challenges to monitor the jobs. I am using zipkin and graphana. Below things are actually required.

1. Lets say job is running every hour - Now need to know when execution started and when finished.
2. Successfull job count
3. Failed job count
4. Job wise duration as well

**Comment by msolli** [comment]
The [logging affordance](https://github.com/msolli/proletarian?tab=readme-ov-file#logging) should be able to help you implement your requirements.

The logger function that you provide via the `:proletarian/log` option will be called by Proletarian whenever anything interesting happens to a job. You might be interested in the `:proletarian.worker/handling-job` and `:proletarian.worker/job-finished` events for when a job is started and finished, and the `:proletarian.worker/handle-job-exception` or `:proletarian.retry/not-retrying` events for every time a job fails and when a job finally fails because all retries have fail, respectively.

> 3. Job wise duration as well

You won't get this number from Proletarian currently, but you could keep track of start and end times of job-ids and compute the duration from those.
